# Node.js でビルド・テストを実行する。バージョンは .node-version に記載されているものを利用する

name: Node CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  node-ci:
    name: Node CI
    uses: book000/templates/.github/workflows/reusable-nodejs-ci.yml@224a681f582a2bb48934752864be4f4565ca0b23 # master
